name: frontendemart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.5
  intl_phone_field: ^3.2.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^6.1.3
  flutter_facebook_auth: ^6.0.4
  carousel_slider: ^5.1.1
  flutter_3d_objects: ^1.0.2+1
  widget_zoom: ^0.0.4
  url_launcher: ^6.3.0
  syncfusion_flutter_pdfviewer: ^30.2.7
  video_player: ^2.7.0
  chewie: ^1.8.1
  easy_localization: ^3.0.8
  geolocator: ^10.1.0
  geocoding: ^2.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo_BlueTransparent.png
    - assets/translations/en.json
    - assets/translations/ar.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  image_path_android: assets/brand/icon.png
